const colors = {
  light: {
    text: "#0a0a0f",
    tint: "#2B7FFF",
    background: "#f5f5ff",
    foreground: "#0a0a0f",
    card: "#ffffff",
    cardForeground: "#0a0a0f",
    primary: "#2B7FFF",
    primaryForeground: "#ffffff",
    secondary: "#7B2FFF",
    secondaryForeground: "#ffffff",
    muted: "#e8e8f0",
    mutedForeground: "#6b6b80",
    accent: "#00D4FF",
    accentForeground: "#0a0a0f",
    destructive: "#EF4444",
    destructiveForeground: "#ffffff",
    border: "#d0d0e0",
    input: "#d0d0e0",
    success: "#22C55E",
    warning: "#F97316",
  },
  dark: {
    text: "#F0F0F8",
    tint: "#2B7FFF",
    background: "#0A0A0F",
    foreground: "#F0F0F8",
    card: "#12121A",
    cardForeground: "#F0F0F8",
    primary: "#2B7FFF",
    primaryForeground: "#ffffff",
    secondary: "#7B2FFF",
    secondaryForeground: "#ffffff",
    muted: "#1E1E2E",
    mutedForeground: "#6B6B80",
    accent: "#00D4FF",
    accentForeground: "#0A0A0F",
    destructive: "#EF4444",
    destructiveForeground: "#ffffff",
    border: "#1E1E2E",
    input: "#1E1E2E",
    success: "#22C55E",
    warning: "#F97316",
  },
  radius: 14,
};

export default colors;
