import { db } from "@workspace/db";
import { templates } from "@workspace/db/schema";
import { sql } from "drizzle-orm";

const SEED_TEMPLATES = [
  {
    title: "Epic Fantasy RPG",
    author: "ForgeStudio",
    description: "A sprawling open-world RPG with branching storylines, deep character progression, and tactical turn-based combat. Includes 40+ hours of handcrafted quests.",
    genre: "RPG",
    artStyle: "Pixel Art",
    difficulty: "Intermediate",
    category: "templates",
    tags: ["open-world", "turn-based", "branching", "magic", "swords"],
    rating: 48,
    reviewCount: 1842,
    usageCount: 12400,
    isPremium: false,
    priceCents: 0,
    badge: "HOT",
    promptHint: "A classic fantasy world with ancient ruins, rival kingdoms, and a dark prophecy threatening the land.",
  },
  {
    title: "Neon Cyberpunk Shooter",
    author: "ForgeStudio",
    description: "Fast-paced top-down shooter set in a rain-soaked megacity. Hacking mechanics, augmentations, and procedurally generated heist missions.",
    genre: "Action",
    artStyle: "Pixel Art",
    difficulty: "Beginner",
    category: "templates",
    tags: ["top-down", "shooter", "cyberpunk", "hacking", "neon"],
    rating: 46,
    reviewCount: 934,
    usageCount: 8700,
    isPremium: false,
    priceCents: 0,
    badge: "NEW",
    promptHint: "A dystopian city where megacorporations rule and underground rebels fight for freedom.",
  },
  {
    title: "Cozy Farming Sim",
    author: "ForgeStudio",
    description: "Relaxing farming and life simulation with seasonal events, NPC relationships, crafting, and a charming village to grow. Perfect for casual players.",
    genre: "Simulation",
    artStyle: "Cartoon",
    difficulty: "Beginner",
    category: "templates",
    tags: ["cozy", "farming", "crafting", "seasons", "relationships"],
    rating: 49,
    reviewCount: 2100,
    usageCount: 21300,
    isPremium: false,
    priceCents: 0,
    badge: null,
    promptHint: "A peaceful countryside where you inherit an old farm and rediscover what matters in life.",
  },
  {
    title: "Horror Survival",
    author: "ForgeStudio",
    description: "Atmospheric survival horror with dynamic AI enemy behavior, resource scarcity, and multiple story-driven endings. Build tension through sound and light design.",
    genre: "Horror",
    artStyle: "Pixel Art",
    difficulty: "Advanced",
    category: "templates",
    tags: ["survival", "horror", "dark", "atmosphere", "multiple-endings"],
    rating: 47,
    reviewCount: 678,
    usageCount: 5400,
    isPremium: true,
    priceCents: 499,
    badge: "PRO",
    promptHint: "An abandoned research facility where something went terribly wrong with the experiments.",
  },
  {
    title: "Roguelike Dungeon Crawler",
    author: "ForgeStudio",
    description: "Infinite replayability with procedurally generated dungeons, 200+ items, 15 character classes, and synergy-based build systems.",
    genre: "Roguelike",
    artStyle: "Pixel Art",
    difficulty: "Intermediate",
    category: "templates",
    tags: ["procedural", "roguelike", "items", "classes", "permadeath"],
    rating: 48,
    reviewCount: 1203,
    usageCount: 9800,
    isPremium: false,
    priceCents: 0,
    badge: null,
    promptHint: "Deep dungeons beneath an ancient city, filled with monsters, traps, and legendary artifacts.",
  },
  {
    title: "Mobile Puzzle Adventure",
    author: "ForgeStudio",
    description: "Elegant puzzle mechanics with a touching narrative. Designed for mobile with one-thumb controls, 100 handcrafted levels, and daily challenges.",
    genre: "Puzzle",
    artStyle: "Cartoon",
    difficulty: "Beginner",
    category: "templates",
    tags: ["puzzle", "mobile", "narrative", "casual", "daily-challenges"],
    rating: 47,
    reviewCount: 445,
    usageCount: 6200,
    isPremium: false,
    priceCents: 0,
    badge: "OFFICIAL",
    promptHint: "A child finds a magical book that comes to life and takes them on a puzzle-filled journey.",
  },
  {
    title: "RTS Battlefield",
    author: "ForgeStudio",
    description: "Classic real-time strategy with base building, unit production, and asymmetric faction design. Includes campaign mode and skirmish AI.",
    genre: "Strategy",
    artStyle: "Isometric",
    difficulty: "Advanced",
    category: "templates",
    tags: ["rts", "base-building", "factions", "campaign", "skirmish"],
    rating: 45,
    reviewCount: 389,
    usageCount: 3100,
    isPremium: true,
    priceCents: 799,
    badge: "PRO",
    promptHint: "Three warring civilizations clash over ancient energy crystals on a fractured planet.",
  },
  {
    title: "Platformer Metroidvania",
    author: "ForgeStudio",
    description: "Exploration-based platformer with ability gating, interconnected world design, hidden secrets, and tight responsive controls.",
    genre: "Platformer",
    artStyle: "Pixel Art",
    difficulty: "Intermediate",
    category: "templates",
    tags: ["metroidvania", "platformer", "exploration", "secrets", "abilities"],
    rating: 48,
    reviewCount: 821,
    usageCount: 7600,
    isPremium: false,
    priceCents: 0,
    badge: null,
    promptHint: "A lone explorer awakens in a vast underground kingdom with no memory, guided only by mysterious echoes.",
  },
  {
    title: "Idle Clicker Empire",
    author: "ForgeStudio",
    description: "Addictive incremental game with prestige mechanics, automation systems, and offline progress. Optimized for long-term retention and monetization.",
    genre: "Idle",
    artStyle: "Cartoon",
    difficulty: "Beginner",
    category: "templates",
    tags: ["idle", "clicker", "prestige", "automation", "offline"],
    rating: 44,
    reviewCount: 234,
    usageCount: 4400,
    isPremium: false,
    priceCents: 0,
    badge: null,
    promptHint: "Start with a single cookie, end with controlling the entire universe through the power of clicking.",
  },
  {
    title: "Tower Defense Pro",
    author: "ForgeStudio",
    description: "Strategic tower defense with 30 tower types, elemental weaknesses, enemy evolution, and a level editor for custom maps.",
    genre: "Strategy",
    artStyle: "Cartoon",
    difficulty: "Intermediate",
    category: "templates",
    tags: ["tower-defense", "strategy", "elements", "level-editor", "waves"],
    rating: 46,
    reviewCount: 567,
    usageCount: 5900,
    isPremium: false,
    priceCents: 0,
    badge: null,
    promptHint: "Ancient kingdoms defend sacred temples against waves of interdimensional invaders.",
  },
];

export async function seedTemplates(): Promise<void> {
  const existing = await db
    .select({ count: sql<number>`count(*)` })
    .from(templates)
    .then((r) => Number(r[0]?.count ?? 0));

  if (existing > 0) return;

  await db.insert(templates).values(SEED_TEMPLATES);
}
