import { db } from "@workspace/db";
import { assets, projects } from "@workspace/db/schema";
import { and, eq } from "drizzle-orm";
import { Router } from "express";
import JSZip from "jszip";
import { requireAuth } from "../middleware/requireAuth";

const router = Router();

type ExportTarget = "godot" | "phaser" | "unity" | "generic";

function godotProjectFile(title: string): string {
  return `; Engine configuration file.
; It's best edited using the editor UI and not directly,
; since the property file format is designed to be user-friendly.

[application]

config/name="${title}"
config/features=PackedStringArray("4.3", "Forward Plus")
config/icon="res://icon.svg"

[rendering]

renderer/rendering_method="forward_plus"
`;
}

function godotMainScene(title: string, protagonist: string): string {
  return `[gd_scene load_steps=2 format=3]

[node name="${title}" type="Node2D"]
script = null

[node name="Player" type="CharacterBody2D" parent="."]
# ${protagonist} - auto-generated by GenForgeAI

[node name="Camera2D" type="Camera2D" parent="Player"]
`;
}

function phaserIndexHtml(title: string, genre: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: #0a0a0f; display: flex; align-items: center; justify-content: center; min-height: 100vh; }
    canvas { display: block; }
  </style>
</head>
<body>
  <script src="https://cdn.jsdelivr.net/npm/phaser@3.88.2/dist/phaser.min.js"></script>
  <script>
    // ${title} — Generated by GenForgeAI
    // Genre: ${genre}
    const config = {
      type: Phaser.AUTO,
      width: 800,
      height: 600,
      backgroundColor: '#0a0a0f',
      scene: {
        preload() {},
        create() {
          this.add.text(400, 300, '${title}', {
            fontSize: '32px',
            fill: '#2B7FFF',
            fontFamily: 'monospace',
          }).setOrigin(0.5);
          this.add.text(400, 360, 'Generated by GenForgeAI', {
            fontSize: '14px',
            fill: '#555',
            fontFamily: 'monospace',
          }).setOrigin(0.5);
        },
        update() {}
      }
    };
    new Phaser.Game(config);
  </script>
</body>
</html>`;
}

function unityGameDataCs(title: string, genre: string, artStyle: string): string {
  return `// ${title} — Game Data
// Auto-generated by GenForgeAI — do not edit manually

using System;
using UnityEngine;

[Serializable]
public class GameData
{
    public string title = ${JSON.stringify(title)};
    public string genre = ${JSON.stringify(genre)};
    public string artStyle = ${JSON.stringify(artStyle)};
}

[Serializable]
public class PlayerStats
{
    public int health = 100;
    public int maxHealth = 100;
    public int attack = 10;
    public int defense = 5;
    public int speed = 5;
    public int level = 1;
    public int experience = 0;
}

public static class GameDataLoader
{
    public static GameData Load() => new GameData();
}
`;
}

function buildReadme(
  title: string,
  target: ExportTarget,
  p: {
    genre: string;
    artStyle: string;
    description: string;
    worldData: Record<string, unknown>;
    storyData: Record<string, unknown>;
    characterData: Record<string, unknown>;
    combatData: Record<string, unknown>;
  }
): string {
  const protagonist = (p.characterData.protagonist as Record<string, unknown>) ?? {};
  const bosses = (p.characterData.bosses as Record<string, unknown>[]) ?? [];

  const setupInstructions: Record<ExportTarget, string> = {
    godot: `1. Open Godot 4.x
2. Choose **Import** → select \`project.godot\`
3. Review \`game-data.json\` for all AI-generated content
4. Move images from \`assets/\` into \`res://assets/\`
5. Build your scenes using the design doc as reference`,
    phaser: `1. Open \`index.html\` in a browser or run \`npx serve .\`
2. Reference \`game-data.json\` for all AI-generated content
3. Add sprites from \`assets/\` to the Phaser preload phase`,
    unity: `1. Create a new Unity 2D project
2. Copy \`Scripts/\` into your project's \`Assets/Scripts/\`
3. Import images from \`assets/\` into \`Assets/Sprites/\``,
    generic: `Review all JSON files for the complete game design data.
Images are in the \`assets/\` folder.`,
  };

  return `# ${title}

> Generated by GenForgeAI — ${new Date().toISOString().split("T")[0]}

## Overview

- **Genre:** ${p.genre}
- **Art Style:** ${p.artStyle}
- **Export Target:** ${target.toUpperCase()}
- **Description:** ${p.description}

## World

**World Name:** ${p.worldData.worldName ?? "Unknown"}

${p.worldData.loreSummary ?? ""}

## Story

**Tagline:** ${p.storyData.tagline ?? ""}

**Core Loop:** ${p.storyData.coreLoop ?? ""}

**Unique Mechanic:** ${p.storyData.uniqueMechanic ?? ""}

## Protagonist

**Name:** ${protagonist.name ?? "Hero"}

${protagonist.backstory ?? ""}

**Abilities:** ${((protagonist.abilities as string[]) ?? []).join(", ")}

## Bosses

${bosses.map((b, i) => `**Boss ${i + 1}: ${b.name ?? "Unknown"}**\n${b.description ?? ""}`).join("\n\n")}

## Combat

**System:** ${p.combatData.combatSystem ?? ""}

**Core Mechanics:** ${((p.combatData.coreMechanics as string[]) ?? []).join(", ")}

## Getting Started

${setupInstructions[target]}
`;
}

router.get("/projects/:id/export", requireAuth, async (req, res) => {
  const projectId = req.params["id"] as string;
  const ownerId = req.user!.sub;
  const target = ((req.query["target"] as string) || "godot") as ExportTarget;

  const [project] = await db
    .select()
    .from(projects)
    .where(and(eq(projects.id, projectId), eq(projects.ownerId, ownerId)))
    .limit(1);

  if (!project) {
    res.status(404).json({ error: "Project not found" });
    return;
  }

  const projectAssets = await db
    .select()
    .from(assets)
    .where(and(eq(assets.projectId, projectId), eq(assets.ownerId, ownerId)));

  const slug = project.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 40);
  const filename = `${slug}-${target}-export.zip`;

  try {
    const zip = new JSZip();

    // ── game-data.json ─────────────────────────────────────────────────────
    const gameData = {
      title: project.title,
      description: project.description,
      genre: project.genre,
      artStyle: project.artStyle,
      platform: project.platform,
      progress: project.progress,
      generatedAt: project.lastGeneratedAt?.toISOString() ?? new Date().toISOString(),
      exportTarget: target,
      exportedBy: "GenForgeAI v1.0",
      story: project.storyData,
      world: project.worldData,
      characters: project.characterData,
      combat: project.combatData,
      assetManifest: project.assetManifest,
    };
    zip.file("game-data.json", JSON.stringify(gameData, null, 2));

    // ── README ─────────────────────────────────────────────────────────────
    zip.file(
      "README.md",
      buildReadme(project.title, target, {
        genre: project.genre,
        artStyle: project.artStyle,
        description: project.description,
        worldData: (project.worldData ?? {}) as Record<string, unknown>,
        storyData: (project.storyData ?? {}) as Record<string, unknown>,
        characterData: (project.characterData ?? {}) as Record<string, unknown>,
        combatData: (project.combatData ?? {}) as Record<string, unknown>,
      })
    );

    // ── Target-specific scaffolding ────────────────────────────────────────
    if (target === "godot") {
      zip.file("project.godot", godotProjectFile(project.title));
      const protagonist =
        ((project.characterData as Record<string, unknown>)?.protagonist as Record<string, unknown>) ?? {};
      zip.file(
        "scenes/main.tscn",
        godotMainScene(project.title, String(protagonist.name ?? "Hero"))
      );
      zip.file("scripts/.gitkeep", "");
    } else if (target === "phaser") {
      zip.file("index.html", phaserIndexHtml(project.title, project.genre));
      zip.file("src/.gitkeep", "");
    } else if (target === "unity") {
      zip.file(
        "Scripts/GameData.cs",
        unityGameDataCs(project.title, project.genre, project.artStyle)
      );
      zip.file("Assets/.gitkeep", "");
    }

    // ── Generated images ───────────────────────────────────────────────────
    for (const asset of projectAssets) {
      if (!asset.url) continue;
      const commaIdx = asset.url.indexOf(",");
      if (commaIdx === -1) continue;
      try {
        const base64 = asset.url.slice(commaIdx + 1);
        const safeName = (asset.name ?? "asset")
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, "-")
          .slice(0, 50);
        const ext = (asset.mimeType ?? "image/png").split("/")[1] ?? "png";
        zip.file(`assets/${asset.category ?? "misc"}/${safeName}.${ext}`, base64, {
          base64: true,
        });
      } catch {
        // skip malformed
      }
    }

    const buf = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });

    res.setHeader("Content-Type", "application/zip");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.setHeader("Content-Length", String(buf.length));
    res.send(buf);
  } catch (err) {
    req.log.error({ err }, "Export failed");
    if (!res.headersSent) {
      res.status(500).json({ error: "Export generation failed" });
    }
  }
});

export default router;
