import { db } from "@workspace/db";
import { assets, projects } from "@workspace/db/schema";
import { and, count, eq } from "drizzle-orm";
import { Router } from "express";
import JSZip from "jszip";
import { routeTask } from "@workspace/ai-router";
import { requireAuth } from "../middleware/requireAuth";

const router = Router();

type ExportTarget = "godot" | "phaser" | "unity" | "generic" | "gamemaker" | "construct" | "unreal" | "rpgmaker";

function godotProjectFile(title: string): string {
  return `; Engine configuration file.
; It's best edited using the editor UI and not directly,
; since the property file format is designed to be user-friendly.

[application]

config/name="${title}"
config/features=PackedStringArray("4.3", "Forward Plus")
config/icon="res://icon.svg"

[rendering]

renderer/rendering_method="forward_plus"
`;
}

function godotMainScene(title: string, protagonist: string): string {
  return `[gd_scene load_steps=2 format=3]

[node name="${title}" type="Node2D"]
script = null

[node name="Player" type="CharacterBody2D" parent="."]
# ${protagonist} - auto-generated by GenForgeAI

[node name="Camera2D" type="Camera2D" parent="Player"]
`;
}

function phaserIndexHtml(title: string, genre: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: #0a0a0f; display: flex; align-items: center; justify-content: center; min-height: 100vh; }
    canvas { display: block; }
  </style>
</head>
<body>
  <script src="https://cdn.jsdelivr.net/npm/phaser@3.88.2/dist/phaser.min.js"></script>
  <script>
    // ${title} — Generated by GenForgeAI
    // Genre: ${genre}
    const config = {
      type: Phaser.AUTO,
      width: 800,
      height: 600,
      backgroundColor: '#0a0a0f',
      scene: {
        preload() {},
        create() {
          this.add.text(400, 300, '${title}', {
            fontSize: '32px',
            fill: '#2B7FFF',
            fontFamily: 'monospace',
          }).setOrigin(0.5);
          this.add.text(400, 360, 'Generated by GenForgeAI', {
            fontSize: '14px',
            fill: '#555',
            fontFamily: 'monospace',
          }).setOrigin(0.5);
        },
        update() {}
      }
    };
    new Phaser.Game(config);
  </script>
</body>
</html>`;
}

function unityGameDataCs(title: string, genre: string, artStyle: string): string {
  return `// ${title} — Game Data
// Auto-generated by GenForgeAI — do not edit manually

using System;
using UnityEngine;

[Serializable]
public class GameData
{
    public string title = ${JSON.stringify(title)};
    public string genre = ${JSON.stringify(genre)};
    public string artStyle = ${JSON.stringify(artStyle)};
}

[Serializable]
public class PlayerStats
{
    public int health = 100;
    public int maxHealth = 100;
    public int attack = 10;
    public int defense = 5;
    public int speed = 5;
    public int level = 1;
    public int experience = 0;
}

public static class GameDataLoader
{
    public static GameData Load() => new GameData();
}
`;
}

// ── GameMaker Studio 2 ─────────────────────────────────────────────────────

function gameMakerYYP(title: string): string {
  const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, "_");
  return JSON.stringify({
    resourceType: "GMProject",
    resourceVersion: "1.7",
    name: slug,
    AudioGroups: [{ resourceType: "GMAudioGroup", resourceVersion: "1.3", name: "audiogroup_default" }],
    configs: { name: "Default", children: [] },
    defaultScriptType: 1,
    TextureGroups: [{ resourceType: "GMTextureGroup", resourceVersion: "1.3", name: "Default" }],
    resources: [],
    generatedBy: "GenForgeAI",
  }, null, 2);
}

function gameMakerPlayerCreate(protagonist: string, genre: string): string {
  return `/// @description ${protagonist} — Create event
/// Generated by GenForgeAI for ${genre}

// Stats
hp    = 100;
maxHp = 100;
speed = 4;
atk   = 10;
dir   = 0;

// State
state = "idle"; // "idle" | "walk" | "attack" | "hurt" | "dead"

// Input flags
inputLeft  = false;
inputRight = false;
inputUp    = false;
inputDown  = false;
inputAtk   = false;
`;
}

function gameMakerPlayerStep(genre: string): string {
  return `/// @description Player — Step event
/// Generated by GenForgeAI for ${genre}

// Gather input
inputLeft  = keyboard_check(vk_left)  || keyboard_check(ord("A"));
inputRight = keyboard_check(vk_right) || keyboard_check(ord("D"));
inputUp    = keyboard_check(vk_up)    || keyboard_check(ord("W"));
inputDown  = keyboard_check(vk_down)  || keyboard_check(ord("S"));
inputAtk   = keyboard_check_pressed(ord("Z")) || keyboard_check_pressed(vk_space);

// Movement
var _dx = (inputRight - inputLeft) * speed;
var _dy = (inputDown  - inputUp)   * speed;
if (place_meeting(x + _dx, y, obj_Solid)) _dx = 0;
if (place_meeting(x, y + _dy, obj_Solid)) _dy = 0;
x += _dx;
y += _dy;

// Attack
if (inputAtk && state != "attack") {
    state = "attack";
    alarm[0] = 20; // reset state after 20 steps
}
`;
}

// ── Construct 3 ────────────────────────────────────────────────────────────

function constructProject(title: string, genre: string): string {
  return JSON.stringify({
    projectType: "application",
    name: title,
    description: `${genre} game generated by GenForgeAI`,
    version: "1.0.0.0",
    generatedBy: "GenForgeAI",
    settings: { fps: 60, width: 1280, height: 720 },
    layouts: [
      { name: "MainMenu",  events: "main-menu.json" },
      { name: "GameScene", events: "game-scene.json" },
    ],
    objectTypes: [
      { name: "Player",  plugin: "Sprite", behaviors: ["Platform", "ScrollTo"] },
      { name: "Enemy",   plugin: "Sprite", behaviors: ["Pathfinding"] },
      { name: "Tilemap", plugin: "Tilemap" },
    ],
  }, null, 2);
}

function constructEventSheet(title: string): string {
  return JSON.stringify({
    name: "Game Scene",
    generatedBy: "GenForgeAI",
    events: [
      {
        type: "block",
        conditions: [{ object: "System", condition: "On start of layout" }],
        actions: [
          { object: "Player", action: "Set position to (100, 100)" },
          { object: "System", action: `Set title to "${title}"` },
        ],
      },
      {
        type: "block",
        conditions: [{ object: "Keyboard", condition: "Key is down", key: "Arrow Left" }],
        actions: [{ object: "Player", action: "Move at angle 180, speed 200" }],
      },
      {
        type: "block",
        conditions: [{ object: "Keyboard", condition: "Key is down", key: "Arrow Right" }],
        actions: [{ object: "Player", action: "Move at angle 0, speed 200" }],
      },
    ],
  }, null, 2);
}

// ── Unreal Engine ──────────────────────────────────────────────────────────

function unrealUProject(title: string): string {
  return JSON.stringify({
    FileVersion: 3,
    EngineAssociation: "5.4",
    Category: "",
    Description: `Generated by GenForgeAI`,
    Modules: [{ Name: title.replace(/\s+/g, ""), Type: "Runtime", LoadingPhase: "Default" }],
    Plugins: [
      { Name: "ModelingToolsEditorMode", Enabled: true },
      { Name: "EnhancedInput",           Enabled: true },
    ],
  }, null, 2);
}

function unrealGameDataHeader(title: string, genre: string, artStyle: string): string {
  const className = title.replace(/[^a-zA-Z0-9]/g, "");
  return `// ${title} — Game Data
// Auto-generated by GenForgeAI — do not edit manually
// Genre: ${genre} | Art Style: ${artStyle}

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/GameModeBase.h"
#include "${className}GameData.generated.h"

USTRUCT(BlueprintType)
struct F${className}PlayerStats
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite) int32 Health    = 100;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) int32 MaxHealth = 100;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) float Speed     = 600.f;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) int32 Attack    = 10;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) int32 Defense   = 5;
    UPROPERTY(EditAnywhere, BlueprintReadWrite) int32 Level     = 1;
};

UCLASS(BlueprintType)
class ${title.toUpperCase().replace(/[^A-Z]/g, "")}_API U${className}GameData : public UObject
{
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FString Title    = TEXT("${title}");
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FString Genre    = TEXT("${genre}");
    UPROPERTY(EditAnywhere, BlueprintReadWrite) FString ArtStyle = TEXT("${artStyle}");
    UPROPERTY(EditAnywhere, BlueprintReadWrite) F${className}PlayerStats PlayerStats;
};
`;
}

// ── RPG Maker MZ ───────────────────────────────────────────────────────────

function rpgMakerPlugin(title: string, genre: string, p: {
  protagonist: Record<string, unknown>;
  storyData: Record<string, unknown>;
  combatData: Record<string, unknown>;
}): string {
  return `/*:
 * @plugindesc ${title} — GenForgeAI Generated Plugin
 * @author GenForgeAI
 *
 * @help
 * Auto-generated for: ${title}
 * Genre: ${genre}
 * Protagonist: ${p.protagonist.name ?? "Hero"}
 * Core Loop: ${p.storyData.coreLoop ?? ""}
 * Combat: ${p.combatData.combatSystem ?? ""}
 *
 * This plugin was generated by GenForgeAI.
 */

(() => {
  "use strict";

  const GAME_DATA = {
    title:     ${JSON.stringify(title)},
    genre:     ${JSON.stringify(genre)},
    protagonist: {
      name:      ${JSON.stringify(p.protagonist.name ?? "Hero")},
      backstory: ${JSON.stringify(p.protagonist.backstory ?? "")},
    },
    coreLoop:  ${JSON.stringify(p.storyData.coreLoop ?? "")},
    tagline:   ${JSON.stringify(p.storyData.tagline ?? "")},
  };

  // Expose via plugin command
  PluginManager.registerCommand("GenForgePlugin", "GetGameData", () => {
    return GAME_DATA;
  });

  // Auto-set window title
  const _Scene_Title_create = Scene_Title.prototype.create;
  Scene_Title.prototype.create = function () {
    _Scene_Title_create.call(this);
    document.title = GAME_DATA.title;
  };
})();
`;
}

// ── LLM-powered gameplay script generation ─────────────────────────────────

async function generateGameplayScript(target: ExportTarget, p: {
  title: string;
  genre: string;
  artStyle: string;
  protagonist: Record<string, unknown>;
  storyData: Record<string, unknown>;
  combatData: Record<string, unknown>;
}): Promise<string | null> {
  const languageMap: Partial<Record<ExportTarget, string>> = {
    godot:     "GDScript 4.x (Godot 4)",
    unity:     "C# (Unity 2022 LTS)",
    gamemaker: "GML (GameMaker Language Studio 2)",
    construct: "JSON event sheet format",
    unreal:    "C++ for Unreal Engine 5",
    rpgmaker:  "JavaScript (RPG Maker MZ plugin)",
    phaser:    "JavaScript (Phaser 3)",
  };
  const lang = languageMap[target];
  if (!lang) return null;

  const systemPrompt = `You are an expert game developer who writes clean, well-commented ${lang} code.
Generate a focused, production-ready gameplay script for the game described below.
Output ONLY the code — no explanations, no markdown code fences.`;

  const userPrompt = `Game: ${p.title}
Genre: ${p.genre}
Art Style: ${p.artStyle}
Protagonist: ${p.protagonist.name ?? "Hero"} — ${p.protagonist.backstory ?? ""}
Core Loop: ${p.storyData.coreLoop ?? ""}
Combat: ${p.combatData.combatSystem ?? ""}

Write a ${lang} script that implements:
1. Player state machine (idle, walk, run, attack, hurt, dead)
2. Basic combat: melee attack, health system, damage feedback
3. Save/load helper that persists player progress
Keep it under 150 lines, modular, and well commented.`;

  try {
    const result = await routeTask("coding", [
      { role: "system", content: systemPrompt },
      { role: "user",   content: userPrompt },
    ]);
    return result.content ?? null;
  } catch {
    return null;
  }
}

function buildReadme(
  title: string,
  target: ExportTarget,
  p: {
    genre: string;
    artStyle: string;
    description: string;
    worldData: Record<string, unknown>;
    storyData: Record<string, unknown>;
    characterData: Record<string, unknown>;
    combatData: Record<string, unknown>;
  }
): string {
  const protagonist = (p.characterData.protagonist as Record<string, unknown>) ?? {};
  const bosses = (p.characterData.bosses as Record<string, unknown>[]) ?? [];

  const setupInstructions: Record<ExportTarget, string> = {
    godot: `1. Open Godot 4.x
2. Choose **Import** → select \`project.godot\`
3. Review \`game-data.json\` for all AI-generated content
4. Move images from \`assets/\` into \`res://assets/\`
5. Open \`scripts/Player.gd\` — AI-generated player controller
6. Build your scenes using the design doc as reference`,
    phaser: `1. Open \`index.html\` in a browser or run \`npx serve .\`
2. Reference \`game-data.json\` for all AI-generated content
3. Add sprites from \`assets/\` to the Phaser preload phase
4. See \`src/Player.js\` for the AI-generated player script`,
    unity: `1. Create a new Unity 2D project
2. Copy \`Scripts/\` into your project's \`Assets/Scripts/\`
3. Import images from \`assets/\` into \`Assets/Sprites/\`
4. See \`Scripts/PlayerController.cs\` for the AI-generated controller`,
    gamemaker: `1. Open GameMaker Studio 2
2. Choose **Open a Project** → select \`project.yyp\`
3. Review \`objects/Player/\` for the AI-generated player object
4. Reference \`game-data.json\` for all design content`,
    construct: `1. Open Construct 3 at editor.construct.net
2. Import \`project.c3proj\` via **Menu → Open**
3. Review \`game-scene.json\` for the AI-generated event sheet
4. Import sprites from \`assets/\` into your sprite objects`,
    unreal: `1. Open Unreal Engine 5.4
2. Double-click the \`.uproject\` file to open the project
3. Copy \`Source/\` into your UE project's \`Source/\` directory
4. Compile from the Unreal Editor or with \`dotnet build\`
5. Reference \`game-data.json\` for all AI-generated design content`,
    rpgmaker: `1. Open RPG Maker MZ
2. Create a new project or open an existing one
3. Copy \`js/plugins/GenForgePlugin.js\` into your project's \`js/plugins/\`
4. Enable the plugin via Plugin Manager
5. Import images from \`assets/\` into your project's image folders`,
    generic: `Review all JSON files for the complete game design data.
Images are in the \`assets/\` folder.`,
  };

  return `# ${title}

> Generated by GenForgeAI — ${new Date().toISOString().split("T")[0]}

## Overview

- **Genre:** ${p.genre}
- **Art Style:** ${p.artStyle}
- **Export Target:** ${target.toUpperCase()}
- **Description:** ${p.description}

## World

**World Name:** ${p.worldData.worldName ?? "Unknown"}

${p.worldData.loreSummary ?? ""}

## Story

**Tagline:** ${p.storyData.tagline ?? ""}

**Core Loop:** ${p.storyData.coreLoop ?? ""}

**Unique Mechanic:** ${p.storyData.uniqueMechanic ?? ""}

## Protagonist

**Name:** ${protagonist.name ?? "Hero"}

${protagonist.backstory ?? ""}

**Abilities:** ${((protagonist.abilities as string[]) ?? []).join(", ")}

## Bosses

${bosses.map((b, i) => `**Boss ${i + 1}: ${b.name ?? "Unknown"}**\n${b.description ?? ""}`).join("\n\n")}

## Combat

**System:** ${p.combatData.combatSystem ?? ""}

**Core Mechanics:** ${((p.combatData.coreMechanics as string[]) ?? []).join(", ")}

## Getting Started

${setupInstructions[target]}
`;
}

router.get("/projects/:id/export", requireAuth, async (req, res) => {
  const projectId = req.params["id"] as string;
  const ownerId = req.user!.sub;
  const target = ((req.query["target"] as string) || "godot") as ExportTarget;

  const [project] = await db
    .select()
    .from(projects)
    .where(and(eq(projects.id, projectId), eq(projects.ownerId, ownerId)))
    .limit(1);

  if (!project) {
    res.status(404).json({ error: "Project not found" });
    return;
  }

  const projectAssets = await db
    .select()
    .from(assets)
    .where(and(eq(assets.projectId, projectId), eq(assets.ownerId, ownerId)));

  const slug = project.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 40);
  const filename = `${slug}-${target}-export.zip`;

  try {
    const zip = new JSZip();

    // ── game-data.json ─────────────────────────────────────────────────────
    const gameData = {
      title: project.title,
      description: project.description,
      genre: project.genre,
      artStyle: project.artStyle,
      platform: project.platform,
      progress: project.progress,
      generatedAt: project.lastGeneratedAt?.toISOString() ?? new Date().toISOString(),
      exportTarget: target,
      exportedBy: "GenForgeAI v1.0",
      story: project.storyData,
      world: project.worldData,
      characters: project.characterData,
      combat: project.combatData,
      assetManifest: project.assetManifest,
    };
    zip.file("game-data.json", JSON.stringify(gameData, null, 2));

    // ── README ─────────────────────────────────────────────────────────────
    zip.file(
      "README.md",
      buildReadme(project.title, target, {
        genre: project.genre,
        artStyle: project.artStyle,
        description: project.description,
        worldData: (project.worldData ?? {}) as Record<string, unknown>,
        storyData: (project.storyData ?? {}) as Record<string, unknown>,
        characterData: (project.characterData ?? {}) as Record<string, unknown>,
        combatData: (project.combatData ?? {}) as Record<string, unknown>,
      })
    );

    // ── Target-specific scaffolding ────────────────────────────────────────
    const cd = (project.characterData ?? {}) as Record<string, unknown>;
    const sd = (project.storyData     ?? {}) as Record<string, unknown>;
    const comd = (project.combatData  ?? {}) as Record<string, unknown>;
    const protagonist = (cd.protagonist as Record<string, unknown>) ?? {};
    const protagonistName = String(protagonist.name ?? "Hero");

    // Kick off LLM code gen in parallel with ZIP assembly (best-effort)
    const llmCodePromise = generateGameplayScript(target, {
      title:     project.title,
      genre:     project.genre,
      artStyle:  project.artStyle,
      protagonist,
      storyData: sd,
      combatData: comd,
    });

    if (target === "godot") {
      zip.file("project.godot", godotProjectFile(project.title));
      zip.file("scenes/main.tscn", godotMainScene(project.title, protagonistName));
      zip.file("scripts/.gitkeep", "");
    } else if (target === "phaser") {
      zip.file("index.html", phaserIndexHtml(project.title, project.genre));
      zip.file("src/.gitkeep", "");
    } else if (target === "unity") {
      zip.file("Scripts/GameData.cs", unityGameDataCs(project.title, project.genre, project.artStyle));
      zip.file("Assets/.gitkeep", "");
    } else if (target === "gamemaker") {
      zip.file("project.yyp", gameMakerYYP(project.title));
      zip.file("objects/Player/Create_0.gml", gameMakerPlayerCreate(protagonistName, project.genre));
      zip.file("objects/Player/Step_0.gml",   gameMakerPlayerStep(project.genre));
      zip.file("sprites/.gitkeep", "");
      zip.file("sounds/.gitkeep", "");
    } else if (target === "construct") {
      zip.file("project.c3proj",  constructProject(project.title, project.genre));
      zip.file("game-scene.json", constructEventSheet(project.title));
      zip.file("images/.gitkeep", "");
    } else if (target === "unreal") {
      const uprojectName = project.title.replace(/[^a-zA-Z0-9]/g, "");
      zip.file(`${uprojectName}.uproject`, unrealUProject(project.title));
      zip.file(`Source/${uprojectName}GameData.h`, unrealGameDataHeader(project.title, project.genre, project.artStyle));
      zip.file("Content/.gitkeep", "");
    } else if (target === "rpgmaker") {
      zip.file("js/plugins/GenForgePlugin.js", rpgMakerPlugin(project.title, project.genre, {
        protagonist,
        storyData: sd,
        combatData: comd,
      }));
      zip.file("img/.gitkeep", "");
    }

    // Attach LLM-generated gameplay script (if it arrived in time)
    const llmCode = await llmCodePromise;
    if (llmCode) {
      const ext: Partial<Record<ExportTarget, string>> = {
        godot: "scripts/Player.gd", phaser: "src/Player.js", unity: "Scripts/PlayerController.cs",
        gamemaker: "objects/Player/LLM_Gameplay.gml", construct: "llm-events.json",
        unreal: "Source/PlayerCharacter.cpp", rpgmaker: "js/plugins/GenForgeGameplay.js",
      };
      const path = ext[target];
      if (path) zip.file(path, llmCode);
    }

    // ── Generated images ───────────────────────────────────────────────────
    for (const asset of projectAssets) {
      if (!asset.url) continue;
      const commaIdx = asset.url.indexOf(",");
      if (commaIdx === -1) continue;
      try {
        const base64 = asset.url.slice(commaIdx + 1);
        const safeName = (asset.name ?? "asset")
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, "-")
          .slice(0, 50);
        const ext = (asset.mimeType ?? "image/png").split("/")[1] ?? "png";
        zip.file(`assets/${asset.category ?? "misc"}/${safeName}.${ext}`, base64, {
          base64: true,
        });
      } catch {
        // skip malformed
      }
    }

    const buf = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });

    res.setHeader("Content-Type", "application/zip");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.setHeader("Content-Length", String(buf.length));
    res.send(buf);
  } catch (err) {
    req.log.error({ err }, "Export failed");
    if (!res.headersSent) {
      res.status(500).json({ error: "Export generation failed" });
    }
  }
});

// ── POST /projects/:id/export/validate — pre-export readiness check ─────────

router.post("/projects/:id/export/validate", requireAuth, async (req, res) => {
  const projectId = req.params["id"] as string;
  const ownerId   = req.user!.sub;

  const [project] = await db
    .select()
    .from(projects)
    .where(and(eq(projects.id, projectId), eq(projects.ownerId, ownerId)))
    .limit(1);

  if (!project) {
    res.status(404).json({ error: "Project not found" });
    return;
  }

  const [assetCount] = await db
    .select({ n: count() })
    .from(assets)
    .where(and(eq(assets.projectId, projectId), eq(assets.ownerId, ownerId)));

  const sd  = (project.storyData     ?? {}) as Record<string, unknown>;
  const wd  = (project.worldData      ?? {}) as Record<string, unknown>;
  const cd  = (project.characterData  ?? {}) as Record<string, unknown>;
  const comd = (project.combatData    ?? {}) as Record<string, unknown>;

  const sdFields  = Object.values(sd).filter(Boolean).length;
  const wdFields  = Object.values(wd).filter(Boolean).length;
  const cdFields  = Object.values(cd).filter(Boolean).length;
  const comdFields = Object.values(comd).filter(Boolean).length;
  const numAssets = assetCount?.n ?? 0;

  type Status = "pass" | "warn" | "fail";
  interface Check { id: string; label: string; status: Status; detail: string; }

  const checks: Check[] = [
    {
      id: "title",
      label: "Project title",
      status: project.title && project.title.length > 1 ? "pass" : "fail",
      detail: project.title || "Missing",
    },
    {
      id: "description",
      label: "Game description",
      status: project.description && project.description.length > 10 ? "pass" : "warn",
      detail: project.description ? `${project.description.slice(0, 40)}…` : "Missing",
    },
    {
      id: "genre",
      label: "Genre defined",
      status: project.genre && project.genre.length > 0 ? "pass" : "fail",
      detail: project.genre || "Not set",
    },
    {
      id: "progress",
      label: "Generation progress",
      status: project.progress >= 80 ? "pass" : project.progress >= 50 ? "warn" : "fail",
      detail: `${project.progress}% complete`,
    },
    {
      id: "story",
      label: "Story data",
      status: sdFields >= 4 ? "pass" : sdFields >= 1 ? "warn" : "fail",
      detail: `${sdFields} fields populated`,
    },
    {
      id: "world",
      label: "World data",
      status: wdFields >= 3 ? "pass" : wdFields >= 1 ? "warn" : "fail",
      detail: `${wdFields} fields populated`,
    },
    {
      id: "characters",
      label: "Character data",
      status: cdFields >= 2 ? "pass" : cdFields >= 1 ? "warn" : "fail",
      detail: `${cdFields} fields populated`,
    },
    {
      id: "combat",
      label: "Combat system",
      status: comdFields >= 2 ? "pass" : comdFields >= 1 ? "warn" : "fail",
      detail: `${comdFields} fields populated`,
    },
    {
      id: "assets",
      label: "Generated assets",
      status: numAssets >= 3 ? "pass" : numAssets >= 1 ? "warn" : "fail",
      detail: `${numAssets} asset${numAssets !== 1 ? "s" : ""} in library`,
    },
    {
      id: "artStyle",
      label: "Art style",
      status: project.artStyle && project.artStyle.length > 0 ? "pass" : "warn",
      detail: project.artStyle || "Not defined",
    },
  ];

  const passed = checks.filter((c) => c.status === "pass").length;
  const warned = checks.filter((c) => c.status === "warn").length;
  const failed = checks.filter((c) => c.status === "fail").length;
  const canExport = failed === 0 && project.progress >= 50;

  res.json({ checks, passed, warned, failed, total: checks.length, canExport });
});

export default router;
