import { Router, type IRouter } from "express";
import aiTasksRouter from "./ai-tasks";
import assetsRouter from "./assets";
import authRouter from "./auth";
import chatRouter from "./chat";
import exportRouter from "./export";
import filesRouter from "./files";
import generateRouter from "./generate";
import qaRouter from "./qa";
import publishRouter from "./publish";
import orchestratorRouter from "./orchestrator";
import imagesRouter from "./images";
import communityRouter from "./community";
import healthRouter from "./health";
import jobsRouter from "./jobs";
import memoryRouter from "./memory";
import notificationsRouter from "./notifications";
import projectChatRouter from "./projectChat";
import projectsRouter from "./projects";
import telemetryRouter from "./telemetry";
import templatesRouter from "./templates";
import usersRouter from "./users";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(projectsRouter);
router.use(aiTasksRouter);
router.use(assetsRouter);
router.use(chatRouter);
router.use(generateRouter);
router.use(exportRouter);
router.use(filesRouter);
router.use(qaRouter);
router.use(publishRouter);
router.use(orchestratorRouter);
router.use(imagesRouter);
router.use(communityRouter);
router.use(jobsRouter);
router.use(memoryRouter);
router.use(notificationsRouter);
router.use(projectChatRouter);
router.use(templatesRouter);
router.use(telemetryRouter);

export default router;
